sudo: required
services:
  - docker

before_install:
  - docker build -t mateombar/react-test f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t mateombar/multi-client ./client
  - docker build -t mateombar/multi-nginx ./nginx
  - docker build -t mateombar/multi-server ./server
  - docker build -t mateombar/multi-worker ./worker
